### ISSUE TITLE
Support for Gnome 3.20

### ISSUE THREAD

**Issue by unixfox** [jenslody/gnome-shell-extension-panel-osd#16]
[Gnome 3.20 was released](https://www.gnome.org/news/2016/03/gnome-3-20-released/) yesterday, can you update this extension for the new version ?
I just tested and this extension works under Gnome 3.20 by modifying `metadata.json` but when I set 100% for horizontal position and 0% for vertical position, the notification appears on right middle and not on bottom right:
![](https://i.unixfox.eu/43-16-27-2016.png)

**Comment by TamasBarta** [comment]
Why was the issue closed?

**Comment by jenslody** [comment]
I don't know if the issue (wrong placement) still happens for the reporter.
I updated the extension to support gnome-shell 3.20 and tested it on Fedora 24 and Rawhide without this issue.
At least not for default gnome-shell with xorg and wayland.
The so called gnome-classic does not work properly, one reason is #6, that means it conflicts with an existing bottom panel, but this can be worked around (more or less), by fixing the vertical placement (it's on my todo-list, but without high priority).
But in gnome-classic I seem to be unable to set horizontal placement at all. This might be a conflict with another extension (needed for classic look). I have to investigate further. If that's the case, it's probably not easy fixable in my extension, or even not at all.
But I did not

**Comment by TamasBarta** [comment]
Thanks for the explanation. Are you planning to create a new release? I asked because I created the AUR package for this extension, and I'm waiting for 3.20 compatibility as well. I'll update the AUR package when you release. If you plan to do it later (weeks, months), then I'll have to create a git version of the package.

**Comment by unixfox** [comment]
Sorry I closed the issue without any explanation. I solved my problem by restarting my PC.
