### ISSUE TITLE
Doesn't work as intended when gnome panel is at bottom.

### ISSUE THREAD

**Issue by Thisuu** [jenslody/gnome-shell-extension-panel-osd#17]
Hi,
I use mmod-panel extension to place my panel at bottom of the screen. So i want notifications to appear at the bottom too,right ahead the panel.This doesn't work.
Also in settings when i adjust vertical position to 'bottom' notification goes high instead.
any workaround please?

**Comment by Thisuu** [comment]
![screenshot from 2016-06-21 12-34-25](https://cloud.githubusercontent.com/assets/13273054/16220793/b4784fe4-37ac-11e6-849d-d57bd24ed939.png)
Here's a screenie

**Comment by jenslody** [comment]
Sorry for the late reply.
I'm not sure if it is possible to work around this, maybe for nmod, but there might be (are?) other extensions that manipulate the panel(-position) and if they do it in a different way, it would be impossible to find workarounds for all of them.
Nevertheless, I will look into it.

Jens
