### ISSUE TITLE
Doesn't calculate correct when the bottom monitor is the primary monitor

### ISSUE THREAD

**Issue by bpearson** [jenslody/gnome-shell-extension-panel-osd#18]
I have found when the bottom monitor is the primary monitor, anything under 100% from the top produces a negative result. 

For some reason if I modify the code to check if yTop is less than 0 then I can multiply that results by -2 and it produces the correct result. I have no idea why its half of the desired result or minus. I just noticed it was out by that. By the way, the -2 is just a guess, it might be just under or over that, -2 just looked close enough for me.

**Comment by jenslody** [comment]
Unfortunately multimonitor setup is a bit tricky, but I will see what I can do.

Jens

**Comment by bpearson** [comment]
Finally got to test this, the y position works, but unfortunately the x position now has a bug. If I set it to 100% (on the right), the width of the notification is smaller. I can work around this by setting the position to 85% (which more or less puts it in the same position as the old 100% setting), but then going back to a single screen, the 85% puts it at about the 85% position. Hope that makes sense?

**Comment by jenslody** [comment]
What are the sizes of your monitors ?
How are they ordered ? Primary monitor below the secondary one ?

**Comment by bpearson** [comment]
Three monitors 2 x 1680x1050 and 1 x 2880x1620 ... the larger one is my primary and below the other 2

**Comment by jenslody** [comment]
Should be fixed in master.

**Comment by bpearson** [comment]
Yep I got the change and reset the x and it looks good
